#pragma once

#include "TimeSyncAuth.h"

// Time-sync preference offsets in /com_prefs. The original single-source
// fields occupy 309..442; additional sources are appended from 443 onward.
#define TIME_SYNC_PREFS_ENABLED_OFFSET 309
#define TIME_SYNC_PREFS_CHANNEL_OFFSET 310
#define TIME_SYNC_PREFS_CHANNEL_NAME_OFFSET 343
#define TIME_SYNC_PREFS_DISPLAY_NAME_OFFSET 375
#define TIME_SYNC_PREFS_PUBLIC_KEY_OFFSET 407
#define TIME_SYNC_PREFS_MAX_FORWARD_STEP_OFFSET 439
#define TIME_SYNC_PREFS_EXTRA_DISPLAY_NAMES_OFFSET 443
#define TIME_SYNC_PREFS_EXTRA_PUBLIC_KEYS_OFFSET 539
#define TIME_SYNC_PREFS_NEXT_OFFSET 635

#define TIME_SYNC_PREFS_EXTRA_SOURCE_COUNT (TIME_SYNC_MAX_SOURCES - 1)
#define TIME_SYNC_PREFS_DISPLAY_NAME_SIZE 32
#define TIME_SYNC_PREFS_EXTRA_DISPLAY_NAMES_SIZE \
  (TIME_SYNC_PREFS_EXTRA_SOURCE_COUNT * TIME_SYNC_PREFS_DISPLAY_NAME_SIZE)
#define TIME_SYNC_PREFS_EXTRA_PUBLIC_KEYS_SIZE \
  (TIME_SYNC_PREFS_EXTRA_SOURCE_COUNT * PUB_KEY_SIZE)
