name: Build Repeater Firmwares

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    tags:
      - 'repeater-*'

jobs:
  build-repeater-firmwares:
    uses: ./.github/workflows/firmware-builder.yml
    with:
      firmware_type: 'repeater'
      release_title_prefix: 'Repeater Firmware'
