name: Build Companion Firmwares

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    tags:
      - 'companion-*'

jobs:
  build-companion-firmwares:
    uses: ./.github/workflows/firmware-builder.yml
    with:
      firmware_type: 'companion'
      release_title_prefix: 'Companion Firmware'
