name: Build Room Server Firmwares

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    tags:
      - 'room-server-*'

jobs:
  build-room-server-firmwares:
    uses: ./.github/workflows/firmware-builder.yml
    with:
      firmware_type: 'room-server'
      release_title_prefix: 'Room Server Firmware'
